"""add_marketplace_features

Revision ID: 32a856673190
Revises: c12477d57224
Create Date: 2026-03-20 04:15:57.660283

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "32a856673190"
down_revision = "c12477d57224"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_categories",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("product_categories_pkey")),
        sa.UniqueConstraint("slug", name="uq_product_category_slug"),
        sa.UniqueConstraint("slug", name=op.f("product_categories_slug_key")),
    )
    op.create_index(
        op.f("ix_product_categories_created_at"),
        "product_categories",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_categories_deleted_at"),
        "product_categories",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_product_categories_slug", "product_categories", ["slug"], unique=False
    )
    op.create_table(
        "donations",
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("donor_name", sa.String(length=255), nullable=False),
        sa.Column("donor_email", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("payment_reference", sa.String(length=255), nullable=False),
        sa.Column("payment_status", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("donations_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("donations_pkey")),
        sa.UniqueConstraint(
            "payment_reference", name=op.f("donations_payment_reference_key")
        ),
    )
    op.create_index(
        "ix_donations_created_at", "donations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_donations_deleted_at"), "donations", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_donations_donor_email", "donations", ["donor_email"], unique=False
    )
    op.create_index(
        "ix_donations_organization_id", "donations", ["organization_id"], unique=False
    )
    op.create_table(
        "newsletter_subscriptions",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("unsubscribe_token", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("newsletter_subscriptions_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("newsletter_subscriptions_pkey")),
        sa.UniqueConstraint("email", "organization_id", name="uq_newsletter_email_org"),
        sa.UniqueConstraint(
            "unsubscribe_token",
            name=op.f("newsletter_subscriptions_unsubscribe_token_key"),
        ),
    )
    op.create_index(
        op.f("ix_newsletter_subscriptions_created_at"),
        "newsletter_subscriptions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_newsletter_subscriptions_deleted_at"),
        "newsletter_subscriptions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_newsletter_subscriptions_email",
        "newsletter_subscriptions",
        ["email"],
        unique=False,
    )
    op.create_index(
        "ix_newsletter_subscriptions_organization_id",
        "newsletter_subscriptions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "cart_items",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("session_token", sa.String(length=255), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(user_id IS NOT NULL AND session_token IS NULL) OR (user_id IS NULL AND session_token IS NOT NULL)",
            name=op.f("cart_items_cart_items_owner_check_check"),
        ),
        sa.CheckConstraint(
            "quantity >= 1 AND quantity <= 100",
            name=op.f("cart_items_cart_items_quantity_check_check"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("cart_items_product_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("cart_items_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cart_items_pkey")),
        sa.UniqueConstraint(
            "session_token", "product_id", name="cart_items_unique_product_session"
        ),
        sa.UniqueConstraint("user_id", "product_id", name="cart_items_unique_product"),
    )
    op.create_index(
        "idx_cart_items_session_token",
        "cart_items",
        ["session_token"],
        unique=False,
        postgresql_where="session_token IS NOT NULL",
    )
    op.create_index(
        "idx_cart_items_updated_at", "cart_items", ["modified_at"], unique=False
    )
    op.create_index(
        "idx_cart_items_user_id",
        "cart_items",
        ["user_id"],
        unique=False,
        postgresql_where="user_id IS NOT NULL",
    )
    op.create_index(
        op.f("ix_cart_items_created_at"), "cart_items", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_cart_items_deleted_at"), "cart_items", ["deleted_at"], unique=False
    )
    op.create_table(
        "product_cart_events",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("product_cart_events_product_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("product_cart_events_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("product_cart_events_pkey")),
    )
    op.create_index(
        "ix_product_cart_events_created_at",
        "product_cart_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_cart_events_deleted_at"),
        "product_cart_events",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_product_cart_events_product_id",
        "product_cart_events",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "product_category_assignments",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_categories.id"],
            name=op.f("product_category_assignments_category_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("product_category_assignments_product_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("product_category_assignments_pkey")),
        sa.UniqueConstraint("product_id", "category_id", name="uq_product_category"),
    )
    op.create_index(
        "ix_product_category_assignments_category_id",
        "product_category_assignments",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_category_assignments_created_at"),
        "product_category_assignments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_category_assignments_deleted_at"),
        "product_category_assignments",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_product_category_assignments_product_id",
        "product_category_assignments",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "product_views",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("product_views_product_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("product_views_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("product_views_pkey")),
    )
    op.create_index(
        "ix_product_views_created_at", "product_views", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_product_views_deleted_at"),
        "product_views",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_product_views_product_id", "product_views", ["product_id"], unique=False
    )
    op.create_table(
        "wishlist_items",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("wishlist_items_product_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("wishlist_items_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("wishlist_items_pkey")),
        sa.UniqueConstraint("user_id", "product_id", name="uq_wishlist_user_product"),
    )
    op.create_index(
        op.f("ix_wishlist_items_created_at"),
        "wishlist_items",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wishlist_items_deleted_at"),
        "wishlist_items",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_wishlist_items_product_id", "wishlist_items", ["product_id"], unique=False
    )
    op.create_index(
        "ix_wishlist_items_user_id", "wishlist_items", ["user_id"], unique=False
    )
    op.create_table(
        "product_reviews",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("review_text", sa.Text(), nullable=True),
        sa.Column("is_verified_purchase", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("product_reviews_order_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("product_reviews_product_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("product_reviews_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("product_reviews_pkey")),
        sa.UniqueConstraint("user_id", "product_id", name="uq_review_user_product"),
    )
    op.create_index(
        op.f("ix_product_reviews_created_at"),
        "product_reviews",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_reviews_deleted_at"),
        "product_reviews",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_product_reviews_product_id", "product_reviews", ["product_id"], unique=False
    )
    op.create_index(
        "ix_product_reviews_rating", "product_reviews", ["rating"], unique=False
    )
    op.create_index(
        "ix_product_reviews_user_id", "product_reviews", ["user_id"], unique=False
    )
    op.add_column(
        "orders", sa.Column("creator_payout_amount", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "creator_payout_amount")
    op.drop_index("ix_product_reviews_user_id", table_name="product_reviews")
    op.drop_index("ix_product_reviews_rating", table_name="product_reviews")
    op.drop_index("ix_product_reviews_product_id", table_name="product_reviews")
    op.drop_index(op.f("ix_product_reviews_deleted_at"), table_name="product_reviews")
    op.drop_index(op.f("ix_product_reviews_created_at"), table_name="product_reviews")
    op.drop_table("product_reviews")
    op.drop_index("ix_wishlist_items_user_id", table_name="wishlist_items")
    op.drop_index("ix_wishlist_items_product_id", table_name="wishlist_items")
    op.drop_index(op.f("ix_wishlist_items_deleted_at"), table_name="wishlist_items")
    op.drop_index(op.f("ix_wishlist_items_created_at"), table_name="wishlist_items")
    op.drop_table("wishlist_items")
    op.drop_index("ix_product_views_product_id", table_name="product_views")
    op.drop_index(op.f("ix_product_views_deleted_at"), table_name="product_views")
    op.drop_index("ix_product_views_created_at", table_name="product_views")
    op.drop_table("product_views")
    op.drop_index(
        "ix_product_category_assignments_product_id",
        table_name="product_category_assignments",
    )
    op.drop_index(
        op.f("ix_product_category_assignments_deleted_at"),
        table_name="product_category_assignments",
    )
    op.drop_index(
        op.f("ix_product_category_assignments_created_at"),
        table_name="product_category_assignments",
    )
    op.drop_index(
        "ix_product_category_assignments_category_id",
        table_name="product_category_assignments",
    )
    op.drop_table("product_category_assignments")
    op.drop_index("ix_product_cart_events_product_id", table_name="product_cart_events")
    op.drop_index(
        op.f("ix_product_cart_events_deleted_at"), table_name="product_cart_events"
    )
    op.drop_index("ix_product_cart_events_created_at", table_name="product_cart_events")
    op.drop_table("product_cart_events")
    op.drop_index(op.f("ix_cart_items_deleted_at"), table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_created_at"), table_name="cart_items")
    op.drop_index(
        "idx_cart_items_user_id",
        table_name="cart_items",
        postgresql_where="user_id IS NOT NULL",
    )
    op.drop_index("idx_cart_items_updated_at", table_name="cart_items")
    op.drop_index(
        "idx_cart_items_session_token",
        table_name="cart_items",
        postgresql_where="session_token IS NOT NULL",
    )
    op.drop_table("cart_items")
    op.drop_index(
        "ix_newsletter_subscriptions_organization_id",
        table_name="newsletter_subscriptions",
    )
    op.drop_index(
        "ix_newsletter_subscriptions_email", table_name="newsletter_subscriptions"
    )
    op.drop_index(
        op.f("ix_newsletter_subscriptions_deleted_at"),
        table_name="newsletter_subscriptions",
    )
    op.drop_index(
        op.f("ix_newsletter_subscriptions_created_at"),
        table_name="newsletter_subscriptions",
    )
    op.drop_table("newsletter_subscriptions")
    op.drop_index("ix_donations_organization_id", table_name="donations")
    op.drop_index("ix_donations_donor_email", table_name="donations")
    op.drop_index(op.f("ix_donations_deleted_at"), table_name="donations")
    op.drop_index("ix_donations_created_at", table_name="donations")
    op.drop_table("donations")
    op.drop_index("ix_product_categories_slug", table_name="product_categories")
    op.drop_index(
        op.f("ix_product_categories_deleted_at"), table_name="product_categories"
    )
    op.drop_index(
        op.f("ix_product_categories_created_at"), table_name="product_categories"
    )
    op.drop_table("product_categories")
    # ### end Alembic commands ###
