"""add_marketplace_features

Revision ID: 4b1f5e85828f
Revises: c12477d57224
Create Date: 2026-03-18 16:19:48.216949

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "4b1f5e85828f"
down_revision = "c12477d57224"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("product_categories_slug_key"), "product_categories", ["slug"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("product_categories_slug_key"), "product_categories", type_="unique"
    )
    # ### end Alembic commands ###
