"""
Property-based tests for Paystack integration - Property 32: Sensitive Data Not in Logs

This module tests that sensitive data (API keys, secrets, payment details)
are not exposed in log entries or error messages.
"""

import re
from unittest.mock import AsyncMock, MagicMock, patch
from uuid import uuid4

import pytest
from hypothesis import given
from hypothesis import strategies as st

from polar.config import settings
from polar.integrations.paystack.service import (
    PaystackAuthenticationError,
    PaystackService,
)
from polar.models.organization import Organization


class TestProperty32SensitiveDataNotInLogs:
    """
    Feature: paystack-integration, Property 32: Sensitive Data Not in Logs

    For any log entry or error message generated by the platform, it should not contain
    sensitive data such as API keys, webhook secrets, or full payment card numbers.
    """

    @pytest.fixture
    def mock_logger(self):
        """Mock logger to capture log entries."""
        logger = MagicMock()
        with patch("polar.integrations.paystack.service.log", logger):
            yield logger

    @pytest.fixture
    def paystack_service(self):
        """Create PaystackService instance for testing."""
        return PaystackService()

    @given(
        email=st.emails(),
        amount=st.integers(min_value=100, max_value=10000000),
        reference=st.text(min_size=10, max_size=50),
        subaccount=st.text(min_size=10, max_size=30),
    )
    @pytest.mark.asyncio
    async def test_transaction_initialization_logs_no_sensitive_data(
        self, mock_logger, paystack_service, email, amount, reference, subaccount
    ):
        """
        Test that transaction initialization logs do not contain sensitive API keys.
        """
        # Mock HTTP client response
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "status": True,
            "data": {
                "authorization_url": "https://checkout.paystack.com/test123",
                "reference": reference,
                "access_code": "test_access_code",
            },
        }

        with patch.object(paystack_service._client, "post", return_value=mock_response):
            await paystack_service.initialize_transaction(
                email=email,
                amount=amount,
                reference=reference,
                subaccount=subaccount,
            )

        # Check all log calls for sensitive data
        for call in mock_logger.info.call_args_list + mock_logger.error.call_args_list:
            log_message = str(call)

            # Ensure API key is not in logs
            assert settings.PAYSTACK_SECRET_KEY not in log_message
            assert "Bearer" not in log_message

            # Ensure no authorization headers are logged
            assert "Authorization" not in log_message

            # Check that only sanitized parameters are logged
            if "paystack.transaction.initialize" in log_message:
                # Should contain safe parameters
                assert email in log_message
                assert str(amount) in log_message
                assert reference in log_message
                assert subaccount in log_message

    @given(
        reference=st.text(min_size=10, max_size=50),
    )
    @pytest.mark.asyncio
    async def test_transaction_verification_logs_no_sensitive_data(
        self, mock_logger, paystack_service, reference
    ):
        """
        Test that transaction verification logs do not contain sensitive API keys.
        """
        # Mock HTTP client response
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "status": True,
            "data": {
                "reference": reference,
                "status": "success",
                "amount": 10000,
            },
        }

        with patch.object(paystack_service._client, "get", return_value=mock_response):
            await paystack_service.verify_transaction(reference)

        # Check all log calls for sensitive data
        for call in mock_logger.info.call_args_list + mock_logger.error.call_args_list:
            log_message = str(call)

            # Ensure API key is not in logs
            assert settings.PAYSTACK_SECRET_KEY not in log_message
            assert "Bearer" not in log_message

            # Ensure no authorization headers are logged
            assert "Authorization" not in log_message

    @given(
        business_name=st.text(min_size=5, max_size=50),
        percentage_charge=st.floats(min_value=1.0, max_value=50.0),
    )
    @pytest.mark.asyncio
    async def test_subaccount_creation_logs_no_sensitive_data(
        self, mock_logger, paystack_service, business_name, percentage_charge
    ):
        """
        Test that subaccount creation logs do not contain sensitive API keys.
        """
        # Mock HTTP client response
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "status": True,
            "data": {
                "subaccount_code": "ACCT_test123",
                "business_name": business_name,
                "percentage_charge": percentage_charge,
                "is_verified": True,
            },
        }

        with patch.object(paystack_service._client, "post", return_value=mock_response):
            await paystack_service.create_subaccount(
                business_name=business_name,
                percentage_charge=percentage_charge,
            )

        # Check all log calls for sensitive data
        for call in mock_logger.info.call_args_list + mock_logger.error.call_args_list:
            log_message = str(call)

            # Ensure API key is not in logs
            assert settings.PAYSTACK_SECRET_KEY not in log_message
            assert "Bearer" not in log_message

            # Ensure no authorization headers are logged
            assert "Authorization" not in log_message

    @given(
        mpesa_number=st.from_regex(r"\+254[17]\d{8}"),
        amount=st.integers(min_value=100, max_value=5000),
    )
    @pytest.mark.asyncio
    async def test_mpesa_verification_logs_no_sensitive_data(
        self, mock_logger, paystack_service, mpesa_number, amount
    ):
        """
        Test that M-Pesa verification logs do not contain sensitive API keys.
        """
        # Mock HTTP client response
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "status": True,
            "data": {
                "reference": "mpesa_verify_test123",
                "status": "success",
                "transfer_code": "TRF_test123",
            },
        }

        with patch.object(paystack_service._client, "post", return_value=mock_response):
            await paystack_service.send_verification_transaction(
                mpesa_number=mpesa_number,
                amount=amount,
            )

        # Check all log calls for sensitive data
        for call in mock_logger.info.call_args_list + mock_logger.error.call_args_list:
            log_message = str(call)

            # Ensure API key is not in logs
            assert settings.PAYSTACK_SECRET_KEY not in log_message
            assert "Bearer" not in log_message

            # Ensure no authorization headers are logged
            assert "Authorization" not in log_message

            # M-Pesa number should be logged (it's not considered sensitive in this context)
            # but ensure it's not in any authorization context

    @given(
        error_message=st.text(min_size=10, max_size=100),
    )
    @pytest.mark.asyncio
    async def test_api_errors_do_not_expose_sensitive_data(
        self, mock_logger, paystack_service, error_message
    ):
        """
        Test that API errors do not expose sensitive data in error messages.
        """
        # Mock HTTP client to raise authentication error
        mock_response = MagicMock()
        mock_response.status_code = 401
        mock_response.json.return_value = {
            "status": False,
            "message": error_message,
        }

        with patch.object(paystack_service._client, "post", return_value=mock_response):
            with pytest.raises(PaystackAuthenticationError):
                await paystack_service.initialize_transaction(
                    email="test@example.com",
                    amount=1000,
                    reference="test_ref",
                    subaccount="test_subaccount",
                )

        # Check all log calls for sensitive data
        for call in mock_logger.info.call_args_list + mock_logger.error.call_args_list:
            log_message = str(call)

            # Ensure API key is not in logs
            assert settings.PAYSTACK_SECRET_KEY not in log_message
            assert "Bearer" not in log_message

            # Ensure no authorization headers are logged
            assert "Authorization" not in log_message

    @pytest.mark.asyncio
    async def test_webhook_signature_verification_logs_no_secrets(self, mock_logger):
        """
        Test that webhook signature verification does not log webhook secrets.
        """
        from polar.integrations.paystack.endpoints import PaystackWebhookEventGetter

        webhook_getter = PaystackWebhookEventGetter(settings.PAYSTACK_WEBHOOK_SECRET)

        # Test with invalid signature
        payload = b'{"event": "charge.success", "data": {"id": "test123"}}'
        invalid_signature = "invalid_signature"

        # Mock request
        mock_request = MagicMock()
        mock_request.body = AsyncMock(return_value=payload)
        mock_request.headers = {"x-paystack-signature": invalid_signature}

        with patch("polar.integrations.paystack.endpoints.log", mock_logger):
            with pytest.raises(Exception):  # Should raise HTTPException
                await webhook_getter(mock_request)

        # Check all log calls for sensitive data
        for call in (
            mock_logger.info.call_args_list
            + mock_logger.error.call_args_list
            + mock_logger.warning.call_args_list
        ):
            log_message = str(call)

            # Ensure webhook secret is not in logs
            assert settings.PAYSTACK_WEBHOOK_SECRET not in log_message

            # Ensure signature values are not fully logged (only boolean indicators)
            assert invalid_signature not in log_message

    @given(
        organization_name=st.text(min_size=5, max_size=50),
    )
    @pytest.mark.asyncio
    async def test_organization_service_logs_no_sensitive_data(
        self, mock_logger, organization_name
    ):
        """
        Test that organization service subaccount creation logs no sensitive data.
        """
        from polar.organization.service import OrganizationService

        # Create mock organization
        organization = Organization(
            id=uuid4(),
            name=organization_name,
            slug=organization_name.lower().replace(" ", "-"),
        )

        # Mock session and repository
        mock_session = MagicMock()
        mock_repository = MagicMock()

        # Mock PaystackService
        with patch("polar.organization.service.paystack") as mock_paystack:
            mock_paystack.create_subaccount.return_value = {
                "subaccount_code": "ACCT_test123",
                "status": "active",
            }

            with patch(
                "polar.organization.service.OrganizationRepository.from_session",
                return_value=mock_repository,
            ):
                mock_repository.update.return_value = organization

                with patch("polar.organization.service.log", mock_logger):
                    service = OrganizationService()

                    try:
                        await service.create_organization_subaccount(
                            mock_session, organization
                        )
                    except Exception:
                        pass  # We're testing logging, not functionality

        # Check all log calls for sensitive data
        for call in mock_logger.info.call_args_list + mock_logger.error.call_args_list:
            log_message = str(call)

            # Ensure API key is not in logs
            assert settings.PAYSTACK_SECRET_KEY not in log_message
            assert "Bearer" not in log_message

            # Ensure no authorization headers are logged
            assert "Authorization" not in log_message

    def test_sensitive_data_patterns_not_in_any_logs(self):
        """
        Test that common sensitive data patterns are not present in any log messages.
        """
        # Define patterns that should never appear in logs
        sensitive_patterns = [
            r"sk_[a-zA-Z0-9]+",  # Paystack secret keys
            r"pk_[a-zA-Z0-9]+",  # Paystack public keys
            r"Bearer\s+[a-zA-Z0-9]+",  # Authorization headers
            r"Authorization:\s*Bearer",  # Authorization header patterns
            r"webhook_secret_[a-zA-Z0-9]+",  # Webhook secrets
            r'password["\']?\s*:\s*["\'][^"\']+["\']',  # Password fields
            r'secret["\']?\s*:\s*["\'][^"\']+["\']',  # Secret fields
        ]

        # This is a meta-test that would be run against actual log output
        # In a real implementation, you would capture logs and test against them

        # For now, we verify the patterns are defined correctly
        for pattern in sensitive_patterns:
            compiled_pattern = re.compile(pattern, re.IGNORECASE)
            assert compiled_pattern is not None

            # Test that the pattern would match actual sensitive data
            if "sk_" in pattern:
                assert compiled_pattern.search("sk_test_1234567890abcdef")
            elif "Bearer" in pattern:
                assert compiled_pattern.search("Bearer sk_test_1234567890abcdef")
